name: flutter_social_embeds
description: Provide a widget to easily embed social media post in flutter using web embed feature by the platform
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.9.0
  url_launcher: ^6.3.1
  localstorage: ^5.0.0
  http: ^1.2.2


dev_dependencies:
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter

